version: '2.1'

services:
  nginx:
    container_name: container_nginx
    build:
      context: nginx
      args:
        MAX_EXECUTION_TIME: ${MAX_EXECUTION_TIME}
        FRONT_SERVER_NAME: ${FRONT_SERVER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front:/front
      - ./logs/nginx/:/var/log/nginx